  name: CI
  on:
    workflow_dispatch:
    push:
      branches:
        - main
  jobs:
    build-n-deploy:
      runs-on: ubuntu-latest
      env:
        GOOS: linux
        GOARCH: amd64

      steps:
        - uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.21.x
            cache: false

        - name: Get Go cached paths
          run: |
            echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
            echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

        - name: Set up dependencies cache
          uses: actions/cache@v3
          with:
            path: |
              ${{ env.cache }}
            key: setup-go-deps-${{ runner.os }}-go-${{ hashFiles('go.sum go.mod') }}

        - run: echo "$GOOS $GOARCH" > /tmp/env

        - name: Set up intermediate built files cache
          uses: actions/cache@v3
          with:
            path: |
              ${{ env.modcache }}
            key: setup-go-build-${{ env.GOOS }}-${{ env.GOARCH }}-${{ runner.os }}-go-${{ hashFiles('**/*.go /tmp/env') }}
            restore-keys: |
              setup-go-build-${{ env.GOOS }}-${{ env.GOARCH }}

        - name: Build Linux binary
          run:  go build

        - name: Build Docker image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/az-appservice .

        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Docker push
          run: docker push ${{ secrets.DOCKER_USERNAME }}/az-appservice

        - name: Login to Azure with Publishing Profile
          run: |
            mkdir ~/.azure
            echo "${{ secrets.AZ_PROFILE }}" > ~/.azure/azure.pubxml

        - name: Deploy to Azure Web App
          run: az webapp restart --name akv-demo-go --resource-group akv-demo-1
